//***********************************************************
//! @file
//! @brief		算術関数
//! @author		Gajumaru
//***********************************************************
#pragma once
#include <cmath>

namespace ob {

    using std::abs;
    using std::acos;
    using std::acosh;
    using std::asin;
    using std::asinh;
    using std::assoc_laguerre;
    using std::assoc_legendre;
    using std::atan;
    using std::atan2;
    using std::atanh;
    using std::beta;
    using std::cbrt;
    using std::ceil;
    using std::comp_ellint_1;
    using std::comp_ellint_2;
    using std::comp_ellint_3;
    using std::copysign;
    using std::cos;
    using std::cosh;
    using std::cyl_bessel_i;
    using std::cyl_bessel_j;
    using std::cyl_bessel_k;
    using std::cyl_neumann;
    using std::ellint_1;
    using std::ellint_2;
    using std::ellint_3;
    using std::erf;
    using std::erfc;
    using std::exp;
    using std::exp2;
    using std::expint;
    using std::expm1;
    using std::fabs;
    using std::fdim;
    using std::floor;
    using std::fma;
    using std::fmax;
    using std::fmin;
    using std::fmod;
    using std::fpclassify;
    using std::frexp;
    using std::hermite;
    using std::hypot;
    using std::ilogb;
    using std::isfinite;
    using std::isgreater;
    using std::isgreaterequal;
    using std::isinf;
    using std::isless;
    using std::islessequal;
    using std::islessgreater;
    using std::isnan;
    using std::isnormal;
    using std::isunordered;
    using std::laguerre;
    using std::ldexp;
    using std::legendre;
    using std::lgamma;
    using std::llrint;
    using std::llround;
    using std::log;
    using std::log10;
    using std::log1p;
    using std::log2;
    using std::logb;
    using std::lrint;
    using std::lround;
    using std::modf;
    using std::nan;
    using std::nearbyint;
    using std::nextafter;
    using std::nexttoward;
    using std::pow;
    using std::remainder;
    using std::remquo;
    using std::riemann_zeta;
    using std::rint;
    using std::round;
    using std::scalbn;
    using std::signbit;
    using std::sin;
    using std::sinh;
    using std::sph_bessel;
    using std::sph_legendre;
    using std::sph_neumann;
    using std::sqrt;
    using std::tan;
    using std::tanh;
    using std::tgamma;
    using std::trunc;

}// namespcae ob