<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<UseWPF>true</UseWPF>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <RootNamespace>$(MSBuildProjectName.Replace(".Texture", ""))</RootNamespace>
	<BaseOutputPath>$(SolutionDir)../../Build/Editor/Plugins/$(ProjectName)</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonView\CommonView.csproj" />
    <ProjectReference Include="..\OctbitEngineAPI.Texture\OctbitEngineAPI.Texture.csproj" />
    <ProjectReference Include="..\OctbitEngineAPI\OctbitEngineAPI.csproj" />
  </ItemGroup>

</Project>
