<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>True</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dirkster.AvalonDock" Version="4.72.1" />
    <PackageReference Include="Dirkster.AvalonDock.Themes.VS2013" Version="4.72.1" />
    <PackageReference Include="LivetCask" Version="4.0.2" />
    <PackageReference Include="ModernWpfUI" Version="0.9.6" />
    <PackageReference Include="OpenCVSharp" Version="2.4.0.1" />
    <PackageReference Include="OpenCvSharp4" Version="4.10.0.20240616" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.10.0.20240616" />
    <PackageReference Include="OpenCvSharp4.Windows" Version="4.10.0.20240616" />
    <PackageReference Include="ReactiveProperty" Version="9.6.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="OutlinerVM.cs">
      <Generator>MSBuild:Compile</Generator>
    </Compile>
  </ItemGroup>

</Project>
