<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>True</UseWindowsForms>
    <ApplicationIcon>Resources\Icons\icon.ico</ApplicationIcon>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
    <BaseOutputPath>$(SolutionDir)../../Build/Editor/$(ProjectName)</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
	<Using Remove="System.Drawing" />
	<Using Remove="System.Windows.Forms" />
  </ItemGroup>
	
  <ItemGroup>
    <None Remove="Resources\Icons\down.png" />
    <None Remove="Resources\Icons\error.png" />
    <None Remove="Resources\Icons\eye_close.png" />
    <None Remove="Resources\Icons\eye_open.png" />
    <None Remove="Resources\Icons\global.png" />
    <None Remove="Resources\Icons\header.png" />
    <None Remove="Resources\Icons\icon.ico" />
    <None Remove="Resources\Icons\icon_design.apd" />
    <None Remove="Resources\Icons\info.png" />
    <None Remove="Resources\Icons\layer.png" />
    <None Remove="Resources\Icons\left.png" />
    <None Remove="Resources\Icons\light.png" />
    <None Remove="Resources\Icons\menu.png" />
    <None Remove="Resources\Icons\move.png" />
    <None Remove="Resources\Icons\Outliner\entity.png" />
    <None Remove="Resources\Icons\Outliner\folder.png" />
    <None Remove="Resources\Icons\Outliner\icon_design.apd" />
    <None Remove="Resources\Icons\pause.png" />
    <None Remove="Resources\Icons\play.png" />
    <None Remove="Resources\Icons\reload.png" />
    <None Remove="Resources\Icons\right.png" />
    <None Remove="Resources\Icons\rotate.png" />
    <None Remove="Resources\Icons\scale.png" />
    <None Remove="Resources\Icons\search.png" />
    <None Remove="Resources\Icons\select.png" />
    <None Remove="Resources\Icons\shading.png" />
    <None Remove="Resources\Icons\snap_move.png" />
    <None Remove="Resources\Icons\snap_rotate.png" />
    <None Remove="Resources\Icons\snap_scale.png" />
    <None Remove="Resources\Icons\step.png" />
    <None Remove="Resources\Icons\stop.png" />
    <None Remove="Resources\Icons\up.png" />
    <None Remove="Resources\Icons\warning.png" />
    <None Remove="Resources\Icons\wire.png" />
    <None Remove="Resources\Icons\wire_shading.png" />
    <None Remove="Resources\Icons\wrap.png" />
    <None Remove="Resources\Splashes\splash_000.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dirkster.AvalonDock" Version="4.72.1" />
    <PackageReference Include="Dirkster.AvalonDock.Themes.VS2013" Version="4.72.1">
      <TreatAsUsed>true</TreatAsUsed>
    </PackageReference>
    <PackageReference Include="LivetCask" Version="4.0.2">
      <TreatAsUsed>true</TreatAsUsed>
    </PackageReference>
    <PackageReference Include="ReactiveProperty" Version="9.6.0">
      <TreatAsUsed>true</TreatAsUsed>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonView\CommonView.csproj" />
    <ProjectReference Include="..\OctbitEngineAPI\OctbitEngineAPI.csproj" />
    <ProjectReference Include="..\OctbitEngine\OctbitEngine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Icons\eye_close.png" />
    <Resource Include="Resources\Icons\eye_open.png" />
    <Resource Include="Resources\Icons\header.png" />
    <Resource Include="Resources\Icons\icon.ico" />
    <Resource Include="Resources\Icons\icon_design.apd" />
    <Resource Include="Resources\Icons\Outliner\entity.png" />
    <Resource Include="Resources\Icons\Outliner\folder.png" />
    <Resource Include="Resources\Icons\Outliner\icon_design.apd" />
    <Resource Include="Resources\Splashes\splash_000.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
