<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Icons\document.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LivetCask" Version="4.0.2" />
    <PackageReference Include="ReactiveProperty" Version="9.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonView\CommonView.csproj" />
    <ProjectReference Include="..\Common\Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Icons\document.png" />
  </ItemGroup>

</Project>
